/*
 * This file was generated automatically by ExtUtils::ParseXS version 3.18 from the
 * contents of Core.xs. Do not edit this file, edit Core.xs instead.
 *
 *    ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

#line 1 "Core.xs"
#include <stdlib.h>
#include <stdint.h>

#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"
#include "ppport.h"

#include <wiringPi.h>
#include <lcd.h>

/*
 * definitions
 */

void registerInterrupt(int pin, int edge, int int_num);
void interruptOne();
void interruptTwo();
static int phys_wpi_map[64];
int physPinToWpi(int wpi_pin);
void callPerlInterrupt();

/*
 * declarations
 */

void registerInterrupt(int pin, int edge, int int_num){
    if (int_num == 1)
        wiringPiISR(pin, edge, &interruptOne);
    if (int_num == 2)
        wiringPiISR(pin, edge, &interruptTwo);
}

void interruptOne(){
    //dSP;
    //PUSHMARK(SP);
    printf("*** interrupt one! ***\n");
    //call_pv("RPi::WiringPi::Interrupt::interrupt_one", G_DISCARD|G_NOARGS);
}

void interruptTwo(){
    dSP;
    PUSHMARK(SP);
    call_pv("RPi::WiringPi::Interrupt::interrupt_two", G_DISCARD|G_NOARGS);
}

int physPinToWpi(int wpi_pin){
    return phys_wpi_map[wpi_pin];
}

void callPerlInterrupt(){
    printf("test");
}

static int phys_wpi_map[64] =
{
  -1, // pin 0 doesn't exist
  -1, -1,
   8, -1,
   9, -1,
   7, 15,
  -1, 16,
   0,  1,
   2, -1,
   3,  4,
  -1,  5,
  12, -1,
  13,  6,
  14, 10,
  -1, 11,
  30, 31,
  21, -1,
  22, 26,
  23, -1,
  24, 27,
  25, 28,
  -1, 29,
  -1, -1,
  -1, -1,
  -1, -1,
  -1, -1,
  -1, -1,
  17, 18,
  19, 20,
  -1, -1,
  -1, -1,
  -1, -1,
  -1, -1,
  -1
};

/*
    not yet implemented

    # core

    extern void pinModeAlt          (int pin, int mode) ;
    extern int  analogRead          (int pin) ;
    extern void analogWrite         (int pin, int value) ;

    # board

    extern          void setPadDrive         (int group, int value) ;
    extern          void pwmToneWrite        (int pin, int freq) ;
    extern          void digitalWriteByte    (int value) ;
    extern unsigned int  digitalReadByte     (void) ;
    extern          void pwmSetMode          (int mode) ;
    extern          void pwmSetClock         (int divisor) ;
    extern          void gpioClockSet        (int pin, int freq) ;

*/

#line 123 "Core.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef dVAR
#  define dVAR		dNOOP
#endif


/* This stuff is not part of the API! You have been warned. */
#ifndef PERL_VERSION_DECIMAL
#  define PERL_VERSION_DECIMAL(r,v,s) (r*1000000 + v*1000 + s)
#endif
#ifndef PERL_DECIMAL_VERSION
#  define PERL_DECIMAL_VERSION \
	  PERL_VERSION_DECIMAL(PERL_REVISION,PERL_VERSION,PERL_SUBVERSION)
#endif
#ifndef PERL_VERSION_GE
#  define PERL_VERSION_GE(r,v,s) \
	  (PERL_DECIMAL_VERSION >= PERL_VERSION_DECIMAL(r,v,s))
#endif
#ifndef PERL_VERSION_LE
#  define PERL_VERSION_LE(r,v,s) \
	  (PERL_DECIMAL_VERSION <= PERL_VERSION_DECIMAL(r,v,s))
#endif

/* XS_INTERNAL is the explicit static-linkage variant of the default
 * XS macro.
 *
 * XS_EXTERNAL is the same as XS_INTERNAL except it does not include
 * "STATIC", ie. it exports XSUB symbols. You probably don't want that
 * for anything but the BOOT XSUB.
 *
 * See XSUB.h in core!
 */


/* TODO: This might be compatible further back than 5.10.0. */
#if PERL_VERSION_GE(5, 10, 0) && PERL_VERSION_LE(5, 15, 1)
#  undef XS_EXTERNAL
#  undef XS_INTERNAL
#  if defined(__CYGWIN__) && defined(USE_DYNAMIC_LOADING)
#    define XS_EXTERNAL(name) __declspec(dllexport) XSPROTO(name)
#    define XS_INTERNAL(name) STATIC XSPROTO(name)
#  endif
#  if defined(__SYMBIAN32__)
#    define XS_EXTERNAL(name) EXPORT_C XSPROTO(name)
#    define XS_INTERNAL(name) EXPORT_C STATIC XSPROTO(name)
#  endif
#  ifndef XS_EXTERNAL
#    if defined(HASATTRIBUTE_UNUSED) && !defined(__cplusplus)
#      define XS_EXTERNAL(name) void name(pTHX_ CV* cv __attribute__unused__)
#      define XS_INTERNAL(name) STATIC void name(pTHX_ CV* cv __attribute__unused__)
#    else
#      ifdef __cplusplus
#        define XS_EXTERNAL(name) extern "C" XSPROTO(name)
#        define XS_INTERNAL(name) static XSPROTO(name)
#      else
#        define XS_EXTERNAL(name) XSPROTO(name)
#        define XS_INTERNAL(name) STATIC XSPROTO(name)
#      endif
#    endif
#  endif
#endif

/* perl >= 5.10.0 && perl <= 5.15.1 */


/* The XS_EXTERNAL macro is used for functions that must not be static
 * like the boot XSUB of a module. If perl didn't have an XS_EXTERNAL
 * macro defined, the best we can do is assume XS is the same.
 * Dito for XS_INTERNAL.
 */
#ifndef XS_EXTERNAL
#  define XS_EXTERNAL(name) XS(name)
#endif
#ifndef XS_INTERNAL
#  define XS_INTERNAL(name) XS(name)
#endif

/* Now, finally, after all this mess, we want an ExtUtils::ParseXS
 * internal macro that we're free to redefine for varying linkage due
 * to the EXPORT_XSUB_SYMBOLS XS keyword. This is internal, use
 * XS_EXTERNAL(name) or XS_INTERNAL(name) in your code if you need to!
 */

#undef XS_EUPXS
#if defined(PERL_EUPXS_ALWAYS_EXPORT)
#  define XS_EUPXS(name) XS_EXTERNAL(name)
#else
   /* default to internal */
#  define XS_EUPXS(name) XS_INTERNAL(name)
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)    S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage        S_croak_xs_usage
#endif

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#line 265 "Core.c"

XS_EUPXS(XS_RPi__WiringPi__Core_wiringPiSetup); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_RPi__WiringPi__Core_wiringPiSetup)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	int	RETVAL;
	dXSTARG;

	RETVAL = wiringPiSetup();
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_RPi__WiringPi__Core_wiringPiSetupSys); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_RPi__WiringPi__Core_wiringPiSetupSys)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	int	RETVAL;
	dXSTARG;

	RETVAL = wiringPiSetupSys();
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_RPi__WiringPi__Core_wiringPiSetupGpio); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_RPi__WiringPi__Core_wiringPiSetupGpio)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	int	RETVAL;
	dXSTARG;

	RETVAL = wiringPiSetupGpio();
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_RPi__WiringPi__Core_wiringPiSetupPhys); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_RPi__WiringPi__Core_wiringPiSetupPhys)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	int	RETVAL;
	dXSTARG;

	RETVAL = wiringPiSetupPhys();
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_RPi__WiringPi__Core_pinMode); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_RPi__WiringPi__Core_pinMode)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "pin, mode");
    {
	int	pin = (int)SvIV(ST(0))
;
	int	mode = (int)SvIV(ST(1))
;

	pinMode(pin, mode);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_RPi__WiringPi__Core_pullUpDnControl); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_RPi__WiringPi__Core_pullUpDnControl)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "pin, pud");
    {
	int	pin = (int)SvIV(ST(0))
;
	int	pud = (int)SvIV(ST(1))
;

	pullUpDnControl(pin, pud);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_RPi__WiringPi__Core_digitalRead); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_RPi__WiringPi__Core_digitalRead)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "pin");
    {
	int	pin = (int)SvIV(ST(0))
;
	int	RETVAL;
	dXSTARG;

	RETVAL = digitalRead(pin);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_RPi__WiringPi__Core_digitalWrite); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_RPi__WiringPi__Core_digitalWrite)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "pin, value");
    {
	int	pin = (int)SvIV(ST(0))
;
	int	value = (int)SvIV(ST(1))
;

	digitalWrite(pin, value);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_RPi__WiringPi__Core_digitalWriteByte); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_RPi__WiringPi__Core_digitalWriteByte)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "value");
    {
	int	value = (int)SvIV(ST(0))
;

	digitalWriteByte(value);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_RPi__WiringPi__Core_pwmWrite); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_RPi__WiringPi__Core_pwmWrite)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "pin, value");
    {
	int	pin = (int)SvIV(ST(0))
;
	int	value = (int)SvIV(ST(1))
;

	pwmWrite(pin, value);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_RPi__WiringPi__Core_getAlt); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_RPi__WiringPi__Core_getAlt)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "pin");
    {
	int	pin = (int)SvIV(ST(0))
;
	int	RETVAL;
	dXSTARG;

	RETVAL = getAlt(pin);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_RPi__WiringPi__Core_piBoardRev); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_RPi__WiringPi__Core_piBoardRev)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	int	RETVAL;
	dXSTARG;

	RETVAL = piBoardRev();
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_RPi__WiringPi__Core_wpiPinToGpio); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_RPi__WiringPi__Core_wpiPinToGpio)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "wpiPin");
    {
	int	wpiPin = (int)SvIV(ST(0))
;
	int	RETVAL;
	dXSTARG;

	RETVAL = wpiPinToGpio(wpiPin);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_RPi__WiringPi__Core_physPinToGpio); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_RPi__WiringPi__Core_physPinToGpio)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "physPin");
    {
	int	physPin = (int)SvIV(ST(0))
;
	int	RETVAL;
	dXSTARG;

	RETVAL = physPinToGpio(physPin);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_RPi__WiringPi__Core_pwmSetRange); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_RPi__WiringPi__Core_pwmSetRange)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "range");
    {
	unsigned int	range = (unsigned int)SvUV(ST(0))
;

	pwmSetRange(range);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_RPi__WiringPi__Core_lcdInit); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_RPi__WiringPi__Core_lcdInit)
{
    dVAR; dXSARGS;
    if (items != 13)
       croak_xs_usage(cv,  "rows, cols, bits, rs, strb, d0, d1, d2, d3, d4, d5, d6, d7");
    {
	int	rows = (int)SvIV(ST(0))
;
	int	cols = (int)SvIV(ST(1))
;
	int	bits = (int)SvIV(ST(2))
;
	int	rs = (int)SvIV(ST(3))
;
	int	strb = (int)SvIV(ST(4))
;
	int	d0 = (int)SvIV(ST(5))
;
	int	d1 = (int)SvIV(ST(6))
;
	int	d2 = (int)SvIV(ST(7))
;
	int	d3 = (int)SvIV(ST(8))
;
	int	d4 = (int)SvIV(ST(9))
;
	int	d5 = (int)SvIV(ST(10))
;
	int	d6 = (int)SvIV(ST(11))
;
	int	d7 = (int)SvIV(ST(12))
;
	int	RETVAL;
	dXSTARG;

	RETVAL = lcdInit(rows, cols, bits, rs, strb, d0, d1, d2, d3, d4, d5, d6, d7);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_RPi__WiringPi__Core_lcdHome); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_RPi__WiringPi__Core_lcdHome)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "fd");
    {
	int	fd = (int)SvIV(ST(0))
;

	lcdHome(fd);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_RPi__WiringPi__Core_lcdClear); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_RPi__WiringPi__Core_lcdClear)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "fd");
    {
	int	fd = (int)SvIV(ST(0))
;

	lcdClear(fd);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_RPi__WiringPi__Core_lcdDisplay); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_RPi__WiringPi__Core_lcdDisplay)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "fd, state");
    {
	int	fd = (int)SvIV(ST(0))
;
	int	state = (int)SvIV(ST(1))
;

	lcdDisplay(fd, state);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_RPi__WiringPi__Core_lcdCursor); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_RPi__WiringPi__Core_lcdCursor)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "fd, state");
    {
	int	fd = (int)SvIV(ST(0))
;
	int	state = (int)SvIV(ST(1))
;

	lcdCursor(fd, state);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_RPi__WiringPi__Core_lcdCursorBlink); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_RPi__WiringPi__Core_lcdCursorBlink)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "fd, state");
    {
	int	fd = (int)SvIV(ST(0))
;
	int	state = (int)SvIV(ST(1))
;

	lcdCursorBlink(fd, state);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_RPi__WiringPi__Core_lcdSendCommand); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_RPi__WiringPi__Core_lcdSendCommand)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "fd, command");
    {
	int	fd = (int)SvIV(ST(0))
;
	char	command = (char)*SvPV_nolen(ST(1))
;

	lcdSendCommand(fd, command);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_RPi__WiringPi__Core_lcdPosition); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_RPi__WiringPi__Core_lcdPosition)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "fd, x, y");
    {
	int	fd = (int)SvIV(ST(0))
;
	int	x = (int)SvIV(ST(1))
;
	int	y = (int)SvIV(ST(2))
;

	lcdPosition(fd, x, y);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_RPi__WiringPi__Core_lcdCharDef); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_RPi__WiringPi__Core_lcdCharDef)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "fd, index, data");
    {
	int	fd = (int)SvIV(ST(0))
;
	int	index = (int)SvIV(ST(1))
;
	unsigned char *	data = (unsigned char *)SvPV_nolen(ST(2))
;

	lcdCharDef(fd, index, data);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_RPi__WiringPi__Core_lcdPutchar); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_RPi__WiringPi__Core_lcdPutchar)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "fd, data");
    {
	int	fd = (int)SvIV(ST(0))
;
	unsigned char	data = (unsigned char)SvUV(ST(1))
;

	lcdPutchar(fd, data);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_RPi__WiringPi__Core_lcdPuts); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_RPi__WiringPi__Core_lcdPuts)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "fd, string");
    {
	int	fd = (int)SvIV(ST(0))
;
	char *	string = (char *)SvPV_nolen(ST(1))
;

	lcdPuts(fd, string);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_RPi__WiringPi__Core_physPinToWpi); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_RPi__WiringPi__Core_physPinToWpi)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "wpi_pin");
    {
	int	wpi_pin = (int)SvIV(ST(0))
;
	int	RETVAL;
	dXSTARG;

	RETVAL = physPinToWpi(wpi_pin);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_RPi__WiringPi__Core_registerInterrupt); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_RPi__WiringPi__Core_registerInterrupt)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "pin, edge, int_num");
    {
	int	pin = (int)SvIV(ST(0))
;
	int	edge = (int)SvIV(ST(1))
;
	int	int_num = (int)SvIV(ST(2))
;

	registerInterrupt(pin, edge, int_num);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_RPi__WiringPi__Core_interruptOne); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_RPi__WiringPi__Core_interruptOne)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    {

	interruptOne();
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_RPi__WiringPi__Core_interruptTwo); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_RPi__WiringPi__Core_interruptTwo)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    {

	interruptTwo();
    }
    XSRETURN_EMPTY;
}

#ifdef __cplusplus
extern "C"
#endif
XS_EXTERNAL(boot_RPi__WiringPi__Core); /* prototype to pass -Wmissing-prototypes */
XS_EXTERNAL(boot_RPi__WiringPi__Core)
{
    dVAR; dXSARGS;
#if (PERL_REVISION == 5 && PERL_VERSION < 9)
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
#ifdef XS_APIVERSION_BOOTCHECK
    XS_APIVERSION_BOOTCHECK;
#endif
    XS_VERSION_BOOTCHECK;

        newXS("RPi::WiringPi::Core::wiringPiSetup", XS_RPi__WiringPi__Core_wiringPiSetup, file);
        newXS("RPi::WiringPi::Core::wiringPiSetupSys", XS_RPi__WiringPi__Core_wiringPiSetupSys, file);
        newXS("RPi::WiringPi::Core::wiringPiSetupGpio", XS_RPi__WiringPi__Core_wiringPiSetupGpio, file);
        newXS("RPi::WiringPi::Core::wiringPiSetupPhys", XS_RPi__WiringPi__Core_wiringPiSetupPhys, file);
        newXS("RPi::WiringPi::Core::pinMode", XS_RPi__WiringPi__Core_pinMode, file);
        newXS("RPi::WiringPi::Core::pullUpDnControl", XS_RPi__WiringPi__Core_pullUpDnControl, file);
        newXS("RPi::WiringPi::Core::digitalRead", XS_RPi__WiringPi__Core_digitalRead, file);
        newXS("RPi::WiringPi::Core::digitalWrite", XS_RPi__WiringPi__Core_digitalWrite, file);
        newXS("RPi::WiringPi::Core::digitalWriteByte", XS_RPi__WiringPi__Core_digitalWriteByte, file);
        newXS("RPi::WiringPi::Core::pwmWrite", XS_RPi__WiringPi__Core_pwmWrite, file);
        newXS("RPi::WiringPi::Core::getAlt", XS_RPi__WiringPi__Core_getAlt, file);
        newXS("RPi::WiringPi::Core::piBoardRev", XS_RPi__WiringPi__Core_piBoardRev, file);
        newXS("RPi::WiringPi::Core::wpiPinToGpio", XS_RPi__WiringPi__Core_wpiPinToGpio, file);
        newXS("RPi::WiringPi::Core::physPinToGpio", XS_RPi__WiringPi__Core_physPinToGpio, file);
        newXS("RPi::WiringPi::Core::pwmSetRange", XS_RPi__WiringPi__Core_pwmSetRange, file);
        newXS("RPi::WiringPi::Core::lcdInit", XS_RPi__WiringPi__Core_lcdInit, file);
        newXS("RPi::WiringPi::Core::lcdHome", XS_RPi__WiringPi__Core_lcdHome, file);
        newXS("RPi::WiringPi::Core::lcdClear", XS_RPi__WiringPi__Core_lcdClear, file);
        newXS("RPi::WiringPi::Core::lcdDisplay", XS_RPi__WiringPi__Core_lcdDisplay, file);
        newXS("RPi::WiringPi::Core::lcdCursor", XS_RPi__WiringPi__Core_lcdCursor, file);
        newXS("RPi::WiringPi::Core::lcdCursorBlink", XS_RPi__WiringPi__Core_lcdCursorBlink, file);
        newXS("RPi::WiringPi::Core::lcdSendCommand", XS_RPi__WiringPi__Core_lcdSendCommand, file);
        newXS("RPi::WiringPi::Core::lcdPosition", XS_RPi__WiringPi__Core_lcdPosition, file);
        newXS("RPi::WiringPi::Core::lcdCharDef", XS_RPi__WiringPi__Core_lcdCharDef, file);
        newXS("RPi::WiringPi::Core::lcdPutchar", XS_RPi__WiringPi__Core_lcdPutchar, file);
        newXS("RPi::WiringPi::Core::lcdPuts", XS_RPi__WiringPi__Core_lcdPuts, file);
        newXS("RPi::WiringPi::Core::physPinToWpi", XS_RPi__WiringPi__Core_physPinToWpi, file);
        newXS("RPi::WiringPi::Core::registerInterrupt", XS_RPi__WiringPi__Core_registerInterrupt, file);
        newXS("RPi::WiringPi::Core::interruptOne", XS_RPi__WiringPi__Core_interruptOne, file);
        newXS("RPi::WiringPi::Core::interruptTwo", XS_RPi__WiringPi__Core_interruptTwo, file);
#if (PERL_REVISION == 5 && PERL_VERSION >= 9)
  if (PL_unitcheckav)
       call_list(PL_scopestack_ix, PL_unitcheckav);
#endif
    XSRETURN_YES;
}

